name: Scheduled Merge

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Checkout image branch
      run: git checkout image

    - name: Merge image branch into master
      run: |
        git fetch origin
        git checkout master
        git pull origin master
        git merge --no-ff image -m "Scheduled merge of image branch into master"
        git push origin master
