name: Scheduled Merge

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout image branch
      uses: actions/checkout@v2
      with:
        ref: image

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Checkout main branch
      run: |
        git checkout main
        git pull origin main

    - name: Merge image into main
      run: |
        git merge --no-ff image -m "Scheduled merge of image branch into main"
        git push origin main
